services:
  - type: web
    name: chatbot-auxiliar-farmacia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: starter  # Plan gratuito con menos restricciones
    healthCheckPath: /health  # Endpoint de salud
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER_KEEP_ALIVE
        value: "true"  # Mantener activo 
  - type: cron
    name: keep-alive-ping
    env: python
    schedule: "*/1 * * * *"   # cada 1 minuto
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive_render.py
    envVars:
      - key: PING_URL
        value: https://asistente-auxiliar-farmacia.onrender.com