services:
  - type: web
    name: chatbot-auxiliar-farmacia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0 
  - type: cron
    name: keep-alive-ping
    env: python
    schedule: "*/1 * * * *"   # cada 1 minuto
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "import os,requests; url=os.environ.get('PING_URL','https://asistente-auxiliar-farmacia.onrender.com/health'); requests.get(url, timeout=15)"
    envVars:
      - key: PING_URL
        value: https://asistente-auxiliar-farmacia.onrender.com/health